name: rotten_tomatoes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  get_it:
  dio:
  equatable:
  dartz:
  shared_preferences:
  go_router:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
